# 短链接服务配置文件

# 服务配置
server:
  # Gin模式: debug或release
  ginMode: "debug"
  
  # 管理API服务配置（创建短链接）
  admin:
    port: 8081
    baseURL: "http://localhost:8081/"
    # IP白名单，允许访问管理API的IP列表
    ipWhitelist:
      - "127.0.0.1"
      - "::1"
      - "192.168.1.0/24"
  
  # 访问API服务配置（短链接重定向）
  access:
    port: 8082
    baseURL: "http://localhost:8082/"

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "gsl"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

# Redis配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 10
  idKeyPrefix: "seq:"  # ID生成器的键前缀
  idStep: 100  # 每次从Redis获取的ID数量

# 缓存配置
cache:
  type: "memory"
  capacity: 1000

# 定时任务配置
tasks:
  # 清理过期短链接的定时任务
  cleanExpiredLinks:
    # cron表达式，默认每天凌晨3点执行
    cron: "0 0 3 * * ?"
    # 是否启用
    enabled: true
    # 每次处理的最大记录数
    batchSize: 1000
    # 历史表前缀
    historyTablePrefix: "short_links_history_"

# JWT配置
jwt:
  # 密钥
  secret: "go-short-link-secret-key"
  # 过期时间（小时）
  expireHours: 24

